defminami/fleamarket_sample_80b

README.md

- 最終課題のデータベース設計
- ER図制作
- 不要な修正やミスを防ぐため。

[WHIP]created_readme

---

db/schema.rb
spec/models/user_spec.rb

test_code1

---

app/models/user.rb
app/views/devise/registrations/new.html.haml
config/locales/ja.yml
spec/models/user_spec.rb

What
エラーメッセージの日本語化
テストコード
Why
アプリケーションの機能

User sign up test code

---

app/assets/stylesheets/_registrations_new.scss
app/assets/stylesheets/product_addresses.scss
app/assets/stylesheets/profiles.scss
app/views/devise/registrations/new.html.haml
app/views/product_addresses/new.html.haml
app/views/profiles/new.html.haml

#WHAT
ユーザー登録の３画面の見た目を統一
#WHY
同じユーザー登録の画面のため、見た目を整えた

ユーザー登録画面の統一

---

app/assets/stylesheets/profiles.scss
app/controllers/profiles_controller.rb
app/views/profiles/edit.html.haml
app/views/profiles/new.html.haml
config/locales/ja.yml
config/routes.rb

#what 
会員情報を編集する機能を実装する
#why
アプリケーションに必要な機能のため

会員情報編集機能の実装

---

.gitignore
app/controllers/items_controller.rb
app/views/items/index.html.haml
app/views/items/new.html.haml
app/views/items/show.html.haml

make_up_more_image

---

app/assets/stylesheets/items.scss

toppageのbackground-imageをscssを書き換えた
pathの問題で本番環境に反映されなかったため

トップページpath変更

---

app/assets/stylesheets/product_addresses.scss
app/assets/stylesheets/profiles.scss
app/controllers/profiles_controller.rb
app/views/devise/registrations/new.html.haml
app/views/product_addresses/edit.html.haml
app/views/product_addresses/new.html.haml
app/views/profiles/edit.html.haml
app/views/profiles/new.html.haml
app/views/users/_mypage_leftside.html.haml

#What
- マイページの実装を行った。
- プロフィールの機能とリンクを追加した。
- 全体のSCSSを統一した。
#WHY
- 本アプリケーションの主幹機能のため
- プロフィールを登録しないと商品の投稿機能が使えない仕様のため。

Back end implementing for my page4

---

app/controllers/items_controller.rb
app/views/items/edit.html.haml
app/views/items/show.html.haml

make_up_item_show_category

---

app/assets/stylesheets/items.scss
app/views/items/index.html.haml

fix_indexItem

---

spec/factories/profiles.rb
spec/models/profile_spec.rb

#what 
プロフィールモデルのテストコードを記載
#why
アプリケーションの必須事項のため

プロフィールモデルのテスト

---

app/assets/stylesheets/_item_show.scss
app/controllers/items_controller.rb
app/views/items/edit.html.haml
app/views/items/new.html.haml

make_up_edit

---

app/assets/stylesheets/_devise.scss
app/assets/stylesheets/items.scss
app/views/items/index.html.haml
app/views/items/show.html.haml
app/views/layouts/application.html.haml

fix_application_haml

---

app/models/user.rb
spec/factories/categories.rb
spec/factories/images.rb
spec/factories/item_images.rb
spec/factories/items.rb
spec/models/item_spec.rb

What
新規登録画面の修正
Why
メールアドレスの文字制限の解除

Items test2

---

README.md
app/assets/javascripts/application.js
app/assets/javascripts/new.category.js
app/assets/javascripts/new_item.js
app/controllers/items_controller.rb
app/models/item.rb
app/views/items/edit.html.haml
app/views/items/show.html.haml
app/views/layouts/application.html.haml

[サーバーサイド]商品情報編集
商品情報の編集機能
本アプリケーションの主幹機能のため。
補足
他メンバーの作業内容を吸収しないと進められない作業があったことや修正点の後発見により複数のブランチを切って作業を行った。
私たちの認識違でコンフリクトを避ける為、単体テストは別途プルリクエストさせてもらいます。

[WHIP]make_up_item_show

---

app/controllers/items_controller.rb
app/views/items/edit.html.haml

[フロントサイド]出品機能
商品出品機能のフロント実装
本アプリケーションの主幹機能のため。
補足  
他メンバーの作業内容を吸収しないと進められない作業があったことや修正点の後発見により複数のブランチを切って作業を行った。  
私たちの認識違いでコンフリクトを避ける為、単体テストは別途プルリクエストさせてもらいます。
マージ履歴　＃32　＃35　＃27 ＃21　＃17 ＃13 ＃9　＃51

[WHIP]created_item_new_front

---

app/controllers/items_controller.rb

[サーバーサイド]商品詳細表示
商品詳細表示のサーバーサイドの実装
本アプリケーションの主幹機能のため。
補足  
他メンバーの作業内容を吸収しないと進められない作業があったことや修正点の後発見により複数のブランチを切って作業を行った。  
マージ履歴　＃51　＃38　＃30

[WHIP]created_item_show_server

---

app/assets/stylesheets/_item_show.scss
app/assets/stylesheets/application.scss
app/assets/stylesheets/likes.scss
app/controllers/likes_controller.rb
app/helpers/likes_helper.rb
app/models/item.rb
app/models/like.rb
app/models/user.rb
app/views/items/show.html.haml
app/views/layouts/application.html.haml
app/views/likes/index.html.haml
config/routes.rb
db/migrate/20200806111607_create_credits.rb
db/migrate/20200818032908_create_likes.rb
db/schema.rb
spec/factories/likes.rb
spec/helpers/likes_helper_spec.rb
spec/models/like_spec.rb
spec/requests/likes_request_spec.rb

いいね機能といいね一覧の実装
• 本アプリケーションの主幹機能と言えるから

[WHIP]created_good

---

app/controllers/likes_controller.rb
app/views/items/show.html.haml
config/routes.rb

ログアウトの状態でも商品詳細に移行できるように実装。
• 本アプリケーションの主幹機能と言えるから。

[WHIP]fix_show_good

---

app/assets/stylesheets/_devise.scss
app/assets/stylesheets/product_addresses.scss
app/assets/stylesheets/profiles.scss
app/assets/stylesheets/users.scss
app/controllers/users/registrations_controller.rb
app/views/devise/registrations/new_product_address.html.haml
app/views/devise/registrations/new_profile.html.haml
app/views/product_addresses/new.html.haml
app/views/profiles/new.html.haml
app/views/users/item_exhibiting.html.haml
app/views/users/item_purchaced.html.haml
app/views/users/item_sold.html.haml
config/routes.rb

- 【サーバサイド】ユーザー新規登録、ログイン(メールアドレスのみ)
- バグを修正
- ウィザード形式の２枚目と３枚の入力画面でバリデーションがかかっていなかった点を修正。
- コードレビューで一度LGTMをもらいマージしていたが、スプリントレビューでチェックした際にバグが見つかったため。
- 詳細なWHAT・WHYと画面のスクリーンショットは以下のプルリクエストの際に送っています。
#47
- ウィザード形式の実装。
#54

User registration debug

---

app/assets/stylesheets/items.scss
app/assets/stylesheets/likes.scss
app/assets/stylesheets/search.scss
app/controllers/items_controller.rb
app/views/items/index.html.haml
app/views/likes/index.html.haml
spec/models/item_spec.rb

- いいね一覧のviewのバグを修正。
- items#indexの仮置きだったおすすめカテゴリーを、あなたへのおすすめ新着商品として実装。
- itemモデルの単体テストの追加分の連絡があったので実装した。
- バグを修正しなければ、本番環境にあげることができないから。
- ユーザーからの信頼を失う危険があるから。

Debugs: Likes and Items 

---

app/assets/stylesheets/_devise.scss
app/assets/stylesheets/credits.scss
app/controllers/items_controller.rb
app/controllers/users/registrations_controller.rb
app/views/credits/new.html.haml
app/views/credits/show.html.haml
app/views/devise/registrations/new_product_address.html.haml
app/views/devise/registrations/new_profile.html.haml
app/views/product_addresses/edit.html.haml
app/views/profiles/edit.html.haml
config/routes.rb

- ユーザー新規登録にバグが見つかったので修正した。
- 【内容】新規登録時、後で登録するボタンで登録をスキップした内容が、マイページから登録できない。
- 【対応】後で登録する機能を取り除いた。
- バグを修正しなければ、主幹機能であるユーザー新規登録が機能しないため。

User registration debug2

---

app/assets/stylesheets/items.scss
app/assets/stylesheets/likes.scss
app/models/item.rb
app/models/user.rb
app/views/items/index.html.haml
app/views/items/show.html.haml
app/views/users/item_purchaced.html.haml
app/views/users/item_sold.html.haml

fix_layout

---

app/views/credits/new.html.haml
app/views/credits/show.html.haml
app/views/items/buy.html.haml
app/views/items/edit.html.haml
app/views/items/search.html.haml
app/views/items/show.html.haml
app/views/likes/index.html.haml
app/views/users/logout.html.haml
config/breadcrumbs.rb
db/schema.rb

- パンくず機能実装。
- 追加がありました。
- 本アプリの根幹機能のため
-  ユーザの利便性向上。
-  現在の推移を見やすくする

Bread scraps2

---

app/assets/javascripts/comment.js
app/assets/stylesheets/_item_buy.scss
app/assets/stylesheets/_item_show.scss
app/assets/stylesheets/items.scss
app/assets/stylesheets/likes.scss
app/controllers/items_controller.rb
app/views/items/buy.html.haml
app/views/items/show.html.haml
config/breadcrumbs.rb

[WHIP]fix_etc

---

app/assets/stylesheets/_item_show.scss
app/assets/stylesheets/items.scss
app/views/items/show.html.haml

[WHIP]fix_show_view

---

app/assets/stylesheets/items.scss
app/views/items/index.html.haml

[WHIP]fix_index_item

---

app/assets/stylesheets/_item_show.scss

- 商品ページのコメント一覧のビュー修正
- 画面縮小した際に、ビューが崩れていました。
- 環境が変わっても変わらず運用出来るため
-  ユーザの利便性向上を上げるため。

comment-view-fix

---

README.md

- ER図の修正、REDEMEの修正
- 追加点、修正点がありました。
- 作業を進めていく過程で修正があったため
-  構築を把握するためです。

ER-fix0825
